### ISSUE TITLE
How to turn off the option of "WHERE 1=1"

### ISSUE THREAD

**Issue by lundeen-bryan** [roobyz/sql-transformer#1]
The ext. injects "1=1" in the WHERE clause by default, but I've been told this can lead to a security vulnerability. Is there a way to modify the packach to opt out the "1=1" snippet?

**Comment by roobyz** [comment]
Thanks for opening the issue. Two points:
1. The setting you are looking for is "**Where One One**". Please have a peek at the README, which describes how to access the user settings in VSCode. Just set it to FALSE (aka untick the checkbox).
2. The 1=1 in the where statement is common practice when building SQL queries programmatically. It always gets ignored by all databases, so there is no tradeoff executing a query with WHERE 1=1. There are really two good use-cases for using this approach:
   - When developing SQL, it makes it easy to quickly comment/uncomment items in the where statement
   - Technically this is a boolean operation, where the second 1 can be set as a variable to 0 so that the query is "turned off" in certain cases. In other words, if you set the SQL to WHERE 1=0 then the query is ignored altogether.

**Comment by lundeen-bryan** [comment]
@roobyz  Thank you for the prompt reply and this is a great extension! although I'm still just a beginner. Anyway, I followed your instructions, but also looked deeper into what you said about the advantages, and it really looks like keeping it "ON" is a better choice. I'll ignore naysayers.  Nonetheless, I now understand where to change the setting:

Ctrl+, opens settings > type "SQL" > select SQL Transformer > uncheck Sql Transformer: Where One One
