### ISSUE TITLE
How do I adjust the "ORDER BY CASE" formatting?

### ISSUE THREAD

**Issue by lundeen-bryan** [roobyz/sql-transformer#2]
I used the following statement on the NORTHWINDS database from Microsoft and wanted to order by a case statement. When SQL Transformer formatted it, the space between "BY" and "CASE" was removed. 
Expected:
```
     SELECT [CustomerID]
          , [CompanyName]
          , [Region]
       FROM [dbo].[Customers]
      WHERE 1=1
   ORDER BY CASE WHEN [Region] IS NULL THEN 1
                ELSE 0
           END
          , [Region]
          , [CustomerID]
```
Actual (Notice the space between "BY" and "CASE" removed by SQL Transformer): 
```
     SELECT [CustomerID]
          , [CompanyName]
          , [Region]
       FROM [dbo].[Customers]
      WHERE 1=1
   ORDER BYCASE WHEN [Region] IS NULL THEN 1
                ELSE 0
           END
          , [Region]
          , [CustomerID]
```

**Comment by roobyz** [comment]
hi @lundeen-bryan,

Thanks for opening the issue. I just resolved the bug. Please update to extension v0.3.10, reload VSCode, and confirm that all is good now.

Cheers,

**Comment by lundeen-bryan** [comment]
Should I clone from the repo? I tried it again and it still didn't fix the space. I tried realoading vscode to see if it would update the ext but that didn't work. 
Here's what it looks like now:
```
     SELECT [CustomerID]
          , [CompanyName]
          , [Region]
       FROM [dbo].[Customers]
      WHERE 1=1
       AND 1=1 ORDER BYCASE
    WHEN [Region] IS NULL THEN 1
    ELSE 0
END
,
[Region]
,
[CustomerID]
```

**Comment by roobyz** [comment]
hi @lundeen-bryan,

As long as the version of your extension (v.0.3.10) is up-to-date in VSCode then it should work, however the extension assumes properly written SQL with valid keywords. When it encounters `ORDER BYCASE` it doesn't understand that you mean `ORDER BY CASE`. You should add the SPACE back between the `BY` and the `CASE` and the extension should format correctly. ;-) 

BTW... if you undo the formatting so that it was the original code, then add the space, and then format, you will not get the extra AND 1=1, which is a result of the incorrectly formatted SQL.

**Comment by roobyz** [comment]
BTW... if you undo the formatting so that it was the original code, then add the space, and then format, you will not get the extra `AND 1=1`, which is a result of the incorrectly formatted SQL. ;-)

**Comment by lundeen-bryan** [comment]
@roobyz Roberto you deserve a lot of credit for this extension thanks so much for the update. I wish I knew how to help you update some of your TODO actions. Maybe connect with me on LinkedIn and someone in my network could also help you. my name there is bryanlundeen no spaces, easy to find. I heard a lot of people talking about snowflake summit so apparently snowflake SQL is pretty popular.
